/* Endianness detector
   (c) Reuben Thomas 2001
*/


#include <stdio.h>

#include "Translate.h"

static char sym[] = "LITTLE_ENDIAN";

int
main(void)
{
  int endianness = 1;
  printf(
    "/* Endian.h\n"
    "   generated by Endian.c\n"
    "*/\n"
    );
  if (*(Byte *)&endianness)
    printf("#define %s", sym);
  else
    printf("/* #undef %s */", sym);
}
