/* Endianness detector
 * Reuben Thomas    13/5/01 */

#include <stdio.h>

#include "Translate.h"

int main(void)
{
  int endianness = 1;

  printf(
    "/* Endian.h\n"
    " * generated by Endian.c */\n"
    "\n");
    if (*(Byte *)&endianness)
      printf("#define LITTLE_ENDIAN");
}
