/* Endianness detector
   (c) Reuben Thomas 2001
*/


#include <stdio.h>

#include "types.h"


static char sym[] = "LITTLE_ENDIAN";

int
main (void)
{
  int endianness = 1;
  printf (
    "/* endian.h\n"
    "   generated by endian.c\n"
    "*/\n\n"
    );
  if (*(Byte *)&endianness)
    printf ("#define %s", sym);
  else
    printf ("/* #undef %s */", sym);
  putchar ('\n');
  return 0;
}
